name: 'Build on push or merge event in develop branch'
on:
    push:
        branches:
            - 'main'

jobs:
    setup-artifact-name:
        runs-on: 'ubuntu-latest'
        outputs:
            artifact_name: ${{ steps.step1.outputs.artifact_name }}
        steps: 
          - id: step1
            run: echo "artifact_name=build_output_$(date "+%Y%m%d%H%M%S")" >> $GITHUB_OUTPUT

    build-output-binary:
        needs: setup-artifact-name
        uses: misitang-nissan/go_test/.github/workflows/build_reusable.yml@main
        with:
            on_branch: ${{ github.action.ref.branch }}
            artifact_name: ${{ needs.setup-artifact-name.outputs.artifact_name }}
