name: 'Auto Build on push/merge to release branch'
on:
    push:
        branches:
            - 'release/*'

jobs:
    setup-artifact-name:
        runs-on: 'ubuntu-latest'
        outputs:
            release_tag: ${{ steps.step1.outputs.release_tag }}
            artifact_name: ${{ steps.step1.outputs.artifact_name }}
        steps: 
          - id: step1
            run: 
                |
                echo "${{ github.event.base_ref }}"
                echo "${{ github.event.ref }}"
                echo "${{ github.action.ref.branch }}"
                echo "release_tag=$(echo ${{ github.push.ref }} | sed 's/release\///g')" >> $GITHUB_OUTPUT
                echo "artifact_name=build_output_$(date "+%Y%m%d%H%M%S")" >> $GITHUB_OUTPUT

        
