name: Run build binary output
on: 
  workflow_call:
    inputs: 
      on_branch:
        required: true
        type: string
        description: 'run build on which branch'
      token:
        required: true
        type: string
        description: 'token for github run'
      artifact_name:
        required: true
        type: string
        description: 'artifact name for build output binary'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.on_branch }}
          fetch-depth: 0
          token: ${{ inputs.token }}
          submodules: true
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: generate code
        run: |
          make init ACTIONS=true
          make code ACTIONS=true
      - name: Run build
        run: |
          export CGO_ENABLED=0
          go build -ldflags '-extldflags=-static' -o ngx-app cmd/front-api/main.go
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
          path: |
            ngx-app
            ./manifest.yml
            ./pipeline/settings/*
