name: Run test
on: workflow_dispatch
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
      - name: Run build
        run: go build -o helleworld
      - uses: actions/upload-artifact@v3
        with:
          name: build_output
          path: helleworld
