
name: 'Process on Github Release published'
on:
  release:
    types: 
      - released

jobs:
  push-to-main:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.NML_BACKEND_BOT_TOKEN }}
      tag_name: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: check_main_branch
        name: Check Main Branch
        run: echo 'main_branch=$(git branch | grep branch)' >> $GITHUB_OUTPUT

      - name: Prepare Main Branch
        if: ${{ steps.check_main_branch.outputs.main_branch }} == ""
        run: git branch main

      - name: Force push to Main Branch
        run: |
          git checkout main
          git merge ${{ env.tag_name }}
