name: 'Release: Archive'

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Input release tag'
        required: true

jobs:
  setup-artifact-name:
    runs-on: 'ubuntu-latest'
    outputs:
        artifact_name: ${{ steps.step1.outputs.artifact_name }}
    steps: 
      - id: step1
        run: echo "artifact_name=build_output_${{ github.event.inputs.tag }}_$(date '+%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
  
  build-archive:
    needs: setup-artifact-name
    uses: ./.github/workflows/build_reusable.yml
    with:
      on_branch: ${{ github.action.ref.branch }}
      artifact_name: ${{ needs.setup-artifact-name.outputs.artifact_name }}

  upload-archive:
    needs: setup-artifact-name
    runs-on: ubuntu-latest
    steps:
      - name: Save binary on GitHub Release
        env:
          GH_TOKEN: ${{ secrets.NML_BACKEND_BOT_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: gh release upload ${{ github.event.inputs.tag }} ${{ needs.setup-artifact-name.outputs.artifact_name }} --clobber