name: 'Upload Github Release Assets'

on:
    workflow_call:
        inputs:
            release_tag:
                required: true
                type: string
                description: 'Github Release tag for the asset'
            artifact_name:
                required: true
                type: string
                description: 'artifact name of asset'

jobs:
    download-and-upload:
        runs-on: ubuntu-latest
        env:
            artifact_name: ${{ inputs.artifact_name }}
        steps:
          - id: download
            name: 'download workflow run artifact'
            uses: actions/download-artifact@v3
            with:
                name: ${{ env.artifact_name }}
                path: ${{ env.artifact_name }}
          - name: archive
            run: tar -cvf ${{ env.artifact_name }}.tar ${{ env.artifact_name }}
          - name: Save binary on GitHub Release
            env:
                GH_TOKEN: ${{ secrets.NML_BACKEND_BOT_TOKEN }}
                GH_REPO: ${{ github.repository }}
            run: gh release upload ${{ inputs.release_tag }} ${{ env.artifact_name }}.tar --clobber
          - name: Clear temporary file
            working-directory: ${{ steps.download.outputs.path }}
            run: 
                | 
                rm -rf ${{ env.artifact_name }}
                rm -rf ${{ env.artifact_name }}.tar